<?php 
$speakers = array(
    array(
        'name' => 'Eduardo Garcia - Enzo',
        'image' => 'speaker-enzo.jpg',
        'link' => 'https://www.drupal.org/u/enzo',
        'position' => 'CTO @ Anexus IT',
        'company' => 'Costa Rica',
        'intro' => 'Eduardo is an engineer in Computer Science with emphasis in Information Systems. He is also a Master in Information Systems with emphasis in Project Management. Specializes in web development using PHP/5, information architecture, project management and Unix administration.',
    ),
    array(
        'name' => 'Gerald Villorente',
        'image' => 'speaker-gerald.jpg',
        'link' => 'http://geraldvillorente.github.io/',
        'position' => 'Director @ VielSoft Ltd Co.',
        'company' => 'Philippines',
        'intro' => 'Gerald is an experienced full stack engineer, Linux network and system administration and Dev Ops tasks. He is a passionate open-source software advocate, creates and contributes to open source projects, is active in community meetups and talks, and does mentoring regulary.',
    ),
    array(
        'name' => 'Tom Tran',
        'image' => 'tomtran.jpg',
        'link' => 'https://www.drupal.org/u/tom-tran',
        'position' => 'Director APAC @ FFW, Admin @ Vietnam Drupal Group',
        'company' => 'Germany',
        'intro' => 'Tom is currently the Managing Partner APAC at FFWagency.com, a tech micro-angel and entreprenuer in Vietname. He also works as a consultat at United Nations (UNEscap.org / Satnetasia.org).',
    ),
    array(
        'name' => 'Paul De Paula',
        'image' => 'paul.jpg',
        'link' => 'https://www.drupal.org/u/fusionx1',
        'position' => 'CSE @ Pantheon',
        'company' => 'Philippines',
        'intro' => 'An accomplished Web Developer with a decade of experience in the industry, from Software Development Firms, Digital News and Media, Airline Services to US Government Platforms.',
    ),
    array(
        'name' => 'Suryanto Rachmat',
        'image' => 'suryanto.jpg',
        'link' => 'http://rachmat.net/',
        'position' => 'Open source advocate',
        'company' => 'Indonesia',
        'intro' => 'Suryanto develop various website & web application and an acitve active in some open source CMS community such as Drupal, Mambo, Joomla. His specialities are in content management system, web design, search engine optimization, software development life cycle.',
    ),
    array(
        'name' => 'Roald Umandal',
        'image' => 'roald.jpg',
        'link' => 'https://www.drupal.org/u/roald.umandal',
        'position' => 'Software Engineer @ VielSoft Ltd Co.',
        'company' => 'Philippines',
        'intro' => '',
    ),
    array(
        'name' => 'Colin Sagan',
        'image' => 'colin.png',
        'link' => 'https://www.linkedin.com/in/colinsagan',
        'position' => 'Founder, Mosswood Creative',
        'company' => 'USA',
        'intro' => 'Colin is the founder and lead developer at Mosswood Creative. He has over 10 years of experience in development.',
    ),
    array(
        'name' => 'Rachel Jaro',
        'image' => 'rachel.jpg',
        'link' => 'https://ph.linkedin.com/in/racheljaro',
        'position' => 'Founder @ Koodi Systems, Drupalcamp Organizer',
        'company' => 'Philippines',
        'intro' => 'Rachel is a tech entreprenuer. She started her career as a programmer and became an active community member of the Drupal community. She helped organized many drupal camps before. She has also been a resource speaker about Drupal and web development in general.',
    ),
);
?>