<?php 
$speakers = array(
    array(
        'name' => 'Eduardo Garcia - Enzo',
        'image' => 'speaker-enzo.jpg',
        'link' => 'https://www.drupal.org/u/enzo',
        'position' => 'CTO @ Anexus IT',
        'company' => 'Costa Rica',
        'intro' => 'Eduardo is an engineer in Computer Science with emphasis in Information Systems. He is also a Master in Information Systems with emphasis in Project Management. Specializes in web development using PHP/5, information architecture, project management and Unix administration.',
    ),
    // array(
    //     'name' => 'Gerald Villorente',
    //     'image' => 'speaker-gerald.jpg',
    //     'link' => 'http://geraldvillorente.github.io/',
    //     'position' => 'Director @ VielSoft Ltd Co.',
    //     'company' => 'Philippines',
    //     'intro' => 'Gerald is an experienced full stack engineer, Linux network and system administration and Dev Ops tasks. He is a passionate open-source software advocate, creates and contributes to open source projects, is active in community meetups and talks, and does mentoring regulary.',
    // ),
    array(
        'name' => 'Tom Tran',
        'image' => 'tomtran.jpg',
        'link' => 'https://www.drupal.org/u/tom-tran',
        'position' => 'Director APAC @ FFW, Admin @ Vietnam Drupal Group',
        'company' => 'Germany',
        'intro' => 'Tom is currently the Managing Partner APAC at FFWagency.com, a tech micro-angel and entreprenuer in Vietname. He also works as a consultat at United Nations (UNEscap.org / Satnetasia.org).',
    ),
    array(
        'name' => 'Paul De Paula',
        'image' => 'paul.jpg',
        'link' => 'https://www.drupal.org/u/fusionx1',
        'position' => 'CSE @ Pantheon',
        'company' => 'Philippines',
        'intro' => 'An accomplished Web Developer with a decade of experience in the industry, from Software Development Firms, Digital News and Media, Airline Services to US Government Platforms.',
    ),
    array(
        'name' => 'Suryanto Rachmat',
        'image' => 'suryanto.jpg',
        'link' => 'http://rachmat.net/',
        'position' => 'Open source advocate',
        'company' => 'Indonesia',
        'intro' => 'Suryanto develop various website & web application and an acitve active in some open source CMS community such as Drupal, Mambo, Joomla. His specialities are in content management system, web design, search engine optimization, software development life cycle.',
    ),
    array(
        'name' => 'Roald Umandal',
        'image' => 'roald.jpg',
        'link' => 'https://www.drupal.org/u/roald.umandal',
        'position' => 'Software Engineer @ VielSoft Ltd Co.',
        'company' => 'Philippines',
        'intro' => '',
    ),
    // array(
    //     'name' => 'Colin Sagan',
    //     'image' => 'colin.png',
    //     'link' => 'https://www.linkedin.com/in/colinsagan',
    //     'position' => 'Founder, Mosswood Creative',
    //     'company' => 'USA',
    //     'intro' => 'Colin is the founder and lead developer at Mosswood Creative. He has over 10 years of experience in development.',
    // ),
    array(
        'name' => 'Rachel Jaro',
        'image' => 'rachel.jpg',
        'link' => 'https://ph.linkedin.com/in/racheljaro',
        'position' => 'Founder @ Koodi Systems, Drupalcamp Organizer',
        'company' => 'Philippines',
        'intro' => 'Rachel is a tech entreprenuer. She started her career as a programmer and became an active community member of the Drupal community. She helped organized many drupal camps before. She has also been a resource speaker about Drupal and web development in general.',
    ),
    array(
        'name' => 'Isaac Sabas',
        'image' => 'isaac.jpg',
        'link' => 'https://www.linkedin.com/in/isaacsabas',
        'position' => 'Founder & CEO @ Pandora Security Labs',
        'company' => 'Philippines',
        'intro' => 'Isaac S. Sabas is the founder and CEO of the leading Managed Security Service Provider (MSSP) in the country, Pandora Security Labs. With his professional and academic experiences, he has built an enterprise where its security solutions complement IT departments of organizations to attain effective and efficient security.',
    ),
    array(
        'name' => 'Leolando Tan',
        'image' => 'leolando.jpg',
        'link' => 'https://www.drupal.org/u/leolandotan',
        'position' => 'Developer @ Prometsource',
        'company' => 'Philippines',
        'intro' => 'About 4 years of developing websites using the Drupal CMS. Top 3 contributor in drupalcores.com in PH. Drupal meet-up and Camp Cebu 2015 speaker',
    ),
    array(
        'name' => 'John Ross Castano',
        'image' => 'johnross.jpg',
        'link' => 'https://www.drupal.org/u/johnrosswvsu',
        'position' => 'Developer @ Prometsource',
        'company' => 'Philippines',
        'intro' => 'A certified Grand Master Developer awareded by Acquia. More than 8 years of solid Drupal development experience.',
    ),
    array(
        'name' => 'Ravindra Singh',
        'image' => 'ravindra.jpg',
        'link' => 'https://www.drupal.org/u/ravindrasingh',
        'position' => 'Drupal Architect @ Srijan Technologies',
        'company' => 'India',
        'intro' => 'Ravindra is a Drupal Architect at Srijan Technologies with over seven years of experience in Web Development. He specialises in developing web-based E-commerce applications and social networking applications in Drupal and PHP.',
    ),
    array(
        'name' => 'Joseph Chin',
        'image' => 'Joe_Chin.png',
        'link' => 'https://www.linkedin.com/in/jchin1968',
        'position' => 'Drupal Solution Architect',
        'company' => 'Canada',
        'intro' => 'Joe, a Canadian living in Singapore, has been working with Drupal for over eight years now, starting with Drupal 6. His main focus is solution architecture and site-building, but he also does module development, performance tuning and automated testing with Behat.',
    ),
    array(
        'name' => 'Solihin Jinata',
        'image' => 'Solihin.png',
        'link' => 'https://www.linkedin.com/in/solihin-jinata-sj-a2978549',
        'position' => 'Co-founder and Technical Director @ Pixel Onion',
        'company' => 'Singapore',
        'intro' => 'SJ is the Co-founder and Technical Director at Pixel Onion, an award winning Drupal shop based in Singapore. He eats, sleeps, and breathes Drupal. Since knowing Drupal in 2005, he has helped clients launch complex scalable platforms on Drupal. His knowledge and skills on system and large architecture design have made big complex sites manageable by a small team of people.',
    ),
);
?>